#!/usr/bin/env bash
# Discovers directories containing PKM compound-extension files and
# reconciles them with qmd collections.
#
# Usage:
#   qmd-sync.sh [<dir> ...]          — register/refresh specific directories
#   qmd-sync.sh                      — re-index all registered collections
#   qmd-sync.sh --no-embed           — skip the `qmd embed` step (on by default)
#   qmd-sync.sh --discover <root>    — register every `pkm/` folder under <root>
#                                      that contains at least one PKM file
#
# Each registered directory becomes a qmd collection. Names are derived from
# the path under $HOME, joined with hyphens (e.g. ~/projects/foo/pkm becomes
# `projects-foo-pkm`), so identically-named folders in different trees do not
# collide. Only compound-extension files are indexed
# (*.{ref,synth,temp,index}.md).
#
# Embeddings are generated by default after sync; pass --no-embed to skip.
# Context is auto-generated from the newest session index in each directory.
#
# After any sync, the script warns about registered collections whose
# underlying directories no longer exist (suggests `qmd collection remove`).

set -euo pipefail

PKM_MASK="**/*.{ref,synth,temp,index}.md"
DO_EMBED=true
DISCOVER_ROOT=""
DIRS=()

# --- helpers ---

die() { echo "qmd-sync: error: $*" >&2; exit 1; }
info() { echo "qmd-sync: $*"; }
warn() { echo "qmd-sync: warning: $*" >&2; }

command_exists() { command -v "$1" &>/dev/null; }

usage() {
  echo "Usage: qmd-sync.sh [--no-embed] [--discover <root>] [<dir> ...]"
  echo ""
  echo "  <dir> ...          Register/refresh specific directories as collections"
  echo "  (no args)          Re-index all existing collections"
  echo "  --discover <root>  Find pkm/ folders under <root> and register each"
  echo "  --no-embed         Skip 'qmd embed' (embeddings on by default)"
  exit 0
}

# --- parse args ---

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-embed) DO_EMBED=false; shift ;;
    --discover)
      [[ -n "${2:-}" ]] || die "--discover requires a directory argument"
      DISCOVER_ROOT="$2"; shift 2 ;;
    --help|-h) usage ;;
    -*) die "unknown option: $1" ;;
    *) DIRS+=("$1"); shift ;;
  esac
done

# --- preflight ---

command_exists qmd || die "qmd not found — install via: mise install npm:@tobilu/qmd"

# --- functions ---

list_collection_names() {
  # Names appear as the first token on lines like:
  #   <name> (qmd://<name>/)
  qmd collection list 2>/dev/null | awk '/^[^ 	]+ \(qmd:\/\// { print $1 }'
}

collection_path() {
  # Parses `qmd collection show <name>` for the `Path: <path>` line.
  local name="$1"
  qmd collection show "$name" 2>/dev/null | awk '/^[[:space:]]*Path:/ { sub(/^[[:space:]]*Path:[[:space:]]*/, ""); print; exit }'
}

collection_exists() {
  local name="$1"
  list_collection_names | grep -qx "$name"
}

derive_collection_name() {
  # Path-joined naming: take absolute path, strip $HOME prefix if applicable,
  # strip leading slash, replace remaining slashes/spaces/dots with hyphens,
  # lowercase, and strip leading dashes.
  #   ~/projects/foo/pkm  → projects-foo-pkm
  #   /var/data/pkm       → var-data-pkm
  #   ~/pkm               → pkm
  local dir="$1"
  local abs
  abs="$(cd "$dir" && pwd)"
  local rel
  if [[ "$abs" == "$HOME" ]]; then
    rel="home"
  elif [[ "$abs" == "$HOME"/* ]]; then
    rel="${abs#"$HOME"/}"
  else
    rel="${abs#/}"
  fi
  echo "$rel" | tr '[:upper:]' '[:lower:]' | tr ' ./' '---' | sed 's/^-*//'
}

has_pkm_files() {
  # Recursively check for at least one compound-extension file (any depth).
  local dir="$1"
  find "$dir" \( -name "*.ref.md" -o -name "*.synth.md" -o -name "*.temp.md" -o -name "*.index.md" \) -print -quit 2>/dev/null | grep -q .
}

build_context() {
  # Extract a context description from session index files in the directory.
  local dir="$1"
  local context=""

  # Try to use summary from the newest session index
  local newest_index
  newest_index=$(find "$dir" -maxdepth 1 -name "session-*.index.md" -print 2>/dev/null | sort -r | head -1)
  if [[ -n "$newest_index" ]]; then
    context=$(awk '/^summary:/{gsub(/^summary: *"?|"$/,""); print; exit}' "$newest_index")
  fi

  # Fall back to counting file types
  if [[ -z "$context" ]]; then
    local refs synths temps
    refs=$(find "$dir" -name "*.ref.md" 2>/dev/null | wc -l | tr -d ' ')
    synths=$(find "$dir" -name "*.synth.md" 2>/dev/null | wc -l | tr -d ' ')
    temps=$(find "$dir" -name "*.temp.md" 2>/dev/null | wc -l | tr -d ' ')
    context="PKM collection: ${refs} refs, ${synths} synths, ${temps} temps"
  fi

  echo "$context"
}

sync_directory() {
  local dir="$1"
  dir="$(cd "$dir" && pwd)" # resolve to absolute path

  local name
  name=$(derive_collection_name "$dir")

  if collection_exists "$name"; then
    info "updating collection '$name' ($dir)"
    qmd update 2>&1 | sed 's/^/  /'
  else
    info "adding collection '$name' ($dir)"
    qmd collection add "$dir" --name "$name" --mask "$PKM_MASK" 2>&1 | sed 's/^/  /'

    # Add context
    local context
    context=$(build_context "$dir")
    if [[ -n "$context" ]]; then
      info "adding context for '$name': $context"
      qmd context add "qmd://$name" "$context" 2>&1 | sed 's/^/  /'
    fi
  fi
}

discover_pkm_dirs() {
  local root="$1"
  [[ -d "$root" ]] || die "discover root not found: $root"

  info "discovering pkm/ folders under $root"

  local pkm_dirs=()
  while IFS= read -r dir; do
    if has_pkm_files "$dir"; then
      pkm_dirs+=("$dir")
    fi
  done < <(find "$root" -type d -name "pkm" 2>/dev/null)

  if [[ ${#pkm_dirs[@]} -eq 0 ]]; then
    info "no pkm/ folders with PKM files found under $root"
    return
  fi

  info "found ${#pkm_dirs[@]} pkm folder(s) with PKM files"
  for dir in "${pkm_dirs[@]}"; do
    sync_directory "$dir"
  done
}

warn_dangling_collections() {
  # Report collections whose registered path no longer exists on disk.
  local dangling=()
  while IFS= read -r name; do
    [[ -z "$name" ]] && continue
    local path
    path=$(collection_path "$name")
    if [[ -n "$path" && ! -d "$path" ]]; then
      dangling+=("$name"$'\t'"$path")
    fi
  done < <(list_collection_names)

  if [[ ${#dangling[@]} -gt 0 ]]; then
    warn "${#dangling[@]} collection(s) point to missing directories:"
    for entry in "${dangling[@]}"; do
      local name="${entry%%$'\t'*}"
      local path="${entry#*$'\t'}"
      echo "    $name  →  $path" >&2
    done
    warn "remove with: qmd collection remove <name>"
  fi
}

# --- main ---

if [[ -n "$DISCOVER_ROOT" ]]; then
  discover_pkm_dirs "$DISCOVER_ROOT"
elif [[ ${#DIRS[@]} -gt 0 ]]; then
  for dir in "${DIRS[@]}"; do
    [[ -d "$dir" ]] || die "directory not found: $dir"
    sync_directory "$dir"
  done
else
  # No args: re-sync all existing collections
  info "updating all existing collections"
  qmd update 2>&1 | sed 's/^/  /'
fi

if $DO_EMBED; then
  info "generating embeddings"
  qmd embed 2>&1 | sed 's/^/  /'
fi

warn_dangling_collections

info "done"
